#!/bin/sh

function _usage()
{
	echo "A simple project template creator for Birb2D"
	echo "Commands:"
	echo -e "  -o\tProject output path [required]"
}

function _createProject()
{
	mkdir -p $projectOutputPath
	for i in $(<./project_template/dirlist)
	do
		mkdir -p "$projectOutputPath/$i"
	done
	cp ./project_template/Makefile $projectOutputPath/Makefile
	cp ./project_template/main.cpp $projectOutputPath/src/main.cpp
	mkdir $projectOutputPath/birb2d
	ln -s $(pwd)/src $projectOutputPath/birb2d/src
	ln -s $(pwd)/include $projectOutputPath/birb2d/include
}

for i in "$@"
do
	case $1 in
		--help|help|-h|--h|-help) _usage ; exit 0 ;;
		-o)
			projectOutputPath=$2
			shift 2
			;;
	esac
done

# Check if project name and output path was specified
[ -n $projectOutputPath ] && _createProject || echo "Missing information to create a new project"
