name: GLFW Tests

on:
  push:
    branches: [ GLFW ]
  pull_request:
    branches: [ GLFW ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libglfw3-dev valgrind
    - name: Compile
      run: mkdir build ; cd build ; cmake .. -DGLFW=ON -DNO_SOUND=ON ; make -j4
    - name: Run quick tests
      run: ./test -tce="*rendering*,*audio*,*timer*"
