name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install valgrind libfluidsynth-dev libxmp-dev libflac-dev libopusfile-dev libsdl2-dev
    - name: Compile
      run: mkdir build ; cd build ; cmake .. ; make -j4
    - name: Run tests
      run: cd build/tests ; ./test -tce="*rendering*,*audio*,*timer*"
    - name: Valgrind memcheck
      run: chmod +x ${GITHUB_WORKSPACE}/.github/workflows/valgrind_test.sh ; ${GITHUB_WORKSPACE}/.github/workflows/valgrind_test.sh
