name: Tic-Tac-Toe

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - name: Clone Tic-Tac-Toe
      run: git clone --recursive https://github.com/Toasterbirb/tic-tac-toe
    - name: Update submodules
      run: cd tic-tac-toe ; git submodule update --init --remote
    - name: Compile
      run: cd tic-tac-toe ; mkdir build ; cd build ; cmake .. && make -j$(nproc)
